### PR TITLE
Checking Connection with POST data

### PR DESCRIPTION
**Pull request by drego85**
When testing the connection to the target URL is also important to submit the POST parameters. Script, written correctly, can reject the connection if you do not pass the POST data.

### CODE REVIEW

**Comment by stasinopoulos** [comment]
Hey, the code that you proposed was not working properly that's why I've added an alternative version (https://github.com/stasinopoulos/commix/commit/7c6e3db3268873afef8ce4970331aa33c14f046f) based on your suggestion. Anyway, thanks for the issue.

**Comment by drego85** [comment]
;) thanks!

**Comment by drego85** [comment]
schermata 2015-12-14 alle 12 51 22

Um no...something is wrong!

Today I have no more time, if you can solve yourself. Otherwise tomorrow I try to correct the error ...

Thanks!
Andrea

**Comment by stasinopoulos** [comment]
Hey Andrea, try to use "--update" to get the latest version and then please check again. 
Thanks!

**Comment by stasinopoulos** [comment]
I think is ok now (https://github.com/stasinopoulos/commix/commit/0e1d75119b86616d16b56d4cdbbba7217852e5fa).

**Comment by drego85** [comment]
Perfect, now it all works! In January I introduce your tool in BackBox Linux...

**Comment by stasinopoulos** [comment]
Wow, that's great! Thanks Andrea :)

**Comment by drego85** [comment]
schermata 2015-12-14 alle 14 43 50
Excuse me, I have another problem!

The error you see in the screenshot appears to me only if I added a POST parameter, with GET's all right.

**Comment by stasinopoulos** [comment]
Hmm, sorry but i can't reproduce this error. 
It seems that the problem here is on the server (500 Internal Server Error). 
I've added an exception for that case (https://github.com/stasinopoulos/commix/commit/dbce91664bcc6ab0046f42eafb60787b0e748c8f). Please confirm that is ok now.

**Comment by drego85** [comment]
Very good work ;) now work fine!

Thanks
Andrea

**Pull request closed without merging**
